# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Upgrade system libraries
      run: |
        sudo apt-get update -y
        sudo apt-get -y upgrade
        sudo apt autoremove -y --purge needrestart

    - name: Install Java 1.8
      run: |
        sudo apt-get install -y openjdk-8-jdk
        java -version

    - name: Verify java compile
      run: |
        sudo apt-get install -y git
        git clone https://github.com/LuisJoseSanchez/hello-world-java
        javac hello-world-java/HelloWorld.java
        CLASSPATH=hello-world-java java HelloWorld

    - uses: actions/checkout@v4  # 检出代码，相当于git clone
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/hello-world-java/*.class'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to ECS
        id: deploy-to-webapp
        run: |
          echo TODO
