# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Upgrade system libraries
      run: |
        sudo apt-get update -y
        sudo apt-get -y upgrade
        sudo apt autoremove -y --purge needrestart

    - name: Install Java 1.8
      run: |
        sudo apt-get install -y openjdk-8-jdk
        java -version

    - name: Verify java compile
      run: |
        sudo apt-get install -y git
        git clone https://github.com/LuisJoseSanchez/hello-world-java
        javac hello-world-java/HelloWorld.java
        CLASSPATH=hello-world-java java HelloWorld

    - name: Prepare gradle
      run: |
        # To install gradle7.2 use:
        #sudo apt install snap -y && sudo snap install gradle --classic
        wget https://services.gradle.org/distributions/gradle-8.11.1-bin.zip
        mkdir /opt/gradle
        unzip -d /opt/gradle gradle-8.11.1-bin.zip
        ls /opt/gradle/gradle-8.11.1
        PATH=$PATH:/opt/gradle/gradle-8.11.1/bin gradle -v
        export PATH=$PATH:/opt/gradle/gradle-8.11.1/bin

    - name: Install sdkman
      run: |
        sudo apt install zip -y
        curl -s "https://get.sdkman.io?rcupdate=false" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk version

    - uses: actions/checkout@v4
    - name: Build jar
      run: |
        sdk install springboot
        springboot run src/main/java/com/example/api.java
        PATH=$PATH:/opt/gradle/gradle-8.11.1/bin gradle build
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/hello-world-java/*.class'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to ECS
        id: deploy-to-webapp
        run: |
          echo TODO
